# Generated by Django 4.0.5 on 2022-06-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leafImages')),
                ('prediction', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('queryId', models.IntegerField(primary_key=True, serialize=False)),
                ('query', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='query_images')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField(max_length=2000)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantApp.query')),
            ],
        ),
    ]
